# Generated by Django 5.1 on 2024-08-16 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(default=0, max_length=15),
        ),
    ]
