# Generated by Django 5.1 on 2024-08-16 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident_app', '0002_userprofile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='incident_type',
            field=models.CharField(choices=[('individual', 'Individual'), ('enterprise', 'Enterprise'), ('government', 'Government')], max_length=20),
        ),
    ]
