# Generated by Django 5.1 on 2024-08-16 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident_app', '0003_alter_incident_incident_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='id',
        ),
        migrations.AlterField(
            model_name='incident',
            name='incident_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
