# Generated by Django 5.1 on 2024-08-16 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident_app', '0004_remove_incident_id_alter_incident_incident_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='incident_status',
            field=models.CharField(choices=[('open', 'OPEN'), ('closed', 'CLOSED')], default='OPEN', max_length=10),
        ),
        migrations.AddField(
            model_name='incident',
            name='priority',
            field=models.CharField(choices=[('low', 'LOW'), ('medium', 'MEDIUM'), ('high', 'HIGH')], default='LOW', max_length=20),
        ),
    ]
