# Generated by Django 5.1 on 2024-08-17 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident_app', '0005_incident_incident_status_incident_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='incident_status',
            field=models.CharField(choices=[('open', 'OPEN'), ('in progress', 'IN PROGRESS'), ('closed', 'CLOSED')], default='OPEN', max_length=20),
        ),
    ]
